TESTING PR
maxklema/mie-api pull request #19
Opened 2024-06-19 16:22 UTC by maxklema

2024-06-19 16:32 UTC, horner requested changes
Let’s add the tests and an actiom to run them

2024-06-19 16:33 UTC, horner commented on readme.md
> +## Testing
This is an inline comment

2024-06-19 18:09 UTC, closed without merging

2024-06-20 13:09 UTC, maxklema commented
Reopen branch.

2024-06-20 13:09 UTC, maxklema commented
Re-open branch.